kind: ConfigMap
apiVersion: v1
metadata:
  name: spark-default-configuration
  namespace: experimental
data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

    <configuration>
      <property>
          <name>fs.defaultFS</name>
          <value>hdfs://hdfs-namenodes.experimental.svc.cluster.local:8020</value>
      </property>
    </configuration>

  hdfs-size.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

    <configuration>
    	<property>
    		<name>dfs.replication</name>
    		<value>1</value>
    	</property>
    	<property>
    		<name>dfs.permissions</name>
    		<value>false</value>
    	</property>
    </configuration>